framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default:
                default_middleware:
                    allow_no_handlers: true

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            App\Shared\Domain\Event\DomainEvent: async

when@dev:
    framework:
        messenger:
            transports:
                async: 'sync://'

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
