export const AMENITY_CATEGORIES = [
  {
    label: 'Équipements généraux',
    items: [
      { code: 'wifi', label: 'Wi-Fi' },
      { code: 'air_conditioning', label: 'Climatisation' },
      { code: 'heating', label: 'Chauffage' },
      { code: 'fan', label: 'Ventilateur' },
      { code: 'fireplace', label: 'Cheminée' },
      { code: 'safe', label: 'Coffre-fort' },
      { code: 'iron', label: 'Fer à repasser' },
      { code: 'vacuum', label: 'Aspirateur' },
      { code: 'drying_rack', label: 'Étendoir à linge' },
    ],
  },
  {
    label: 'Cuisine',
    items: [
      { code: 'equipped_kitchen', label: 'Cuisine équipée' },
      { code: 'fridge', label: 'Réfrigérateur' },
      { code: 'oven', label: 'Four' },
      { code: 'microwave', label: 'Micro-ondes' },
      { code: 'dishwasher', label: 'Lave-vaisselle' },
      { code: 'coffee_maker', label: 'Cafetière / Bouilloire' },
      { code: 'toaster', label: 'Grille-pain' },
      { code: 'stove', label: 'Plaques de cuisson' },
      { code: 'kitchen_utensils', label: 'Ustensiles de cuisine' },
      { code: 'ice_maker', label: 'Machine à glaçons' },
    ],
  },
  {
    label: 'Salle de bain',
    items: [
      { code: 'hair_dryer', label: 'Sèche-cheveux' },
      { code: 'bathtub', label: 'Baignoire' },
      { code: 'walk_in_shower', label: 'Douche italienne' },
      { code: 'towels', label: 'Serviettes fournies' },
      { code: 'toiletries', label: "Produits d'accueil" },
      { code: 'washing_machine', label: 'Machine à laver' },
      { code: 'dryer', label: 'Sèche-linge' },
    ],
  },
  {
    label: 'Chambre',
    items: [
      { code: 'bed_linen', label: 'Linge de lit fourni' },
      { code: 'extra_pillows', label: 'Oreillers supplémentaires' },
      { code: 'blankets', label: 'Couvertures' },
      { code: 'blackout_curtains', label: 'Rideaux occultants' },
      { code: 'baby_crib', label: 'Lit bébé' },
      { code: 'wardrobe', label: 'Dressing / Penderie' },
    ],
  },
  {
    label: 'Extérieur',
    items: [
      { code: 'garden', label: 'Jardin' },
      { code: 'terrace', label: 'Terrasse' },
      { code: 'balcony', label: 'Balcon' },
      { code: 'barbecue', label: 'Barbecue' },
      { code: 'outdoor_furniture', label: 'Mobilier de jardin' },
      { code: 'private_pool', label: 'Piscine privée' },
      { code: 'shared_pool', label: 'Piscine partagée' },
      { code: 'hot_tub', label: 'Jacuzzi / Spa' },
      { code: 'private_parking', label: 'Parking privé' },
      { code: 'garage', label: 'Garage' },
      { code: 'parking_spot', label: 'Place de parking' },
      { code: 'fenced_yard', label: 'Cour clôturée' },
    ],
  },
  {
    label: 'Loisirs / Divertissement',
    items: [
      { code: 'tv', label: 'Télévision' },
      { code: 'streaming', label: 'Netflix / Streaming' },
      { code: 'books', label: 'Livres / Bibliothèque' },
      { code: 'board_games', label: 'Jeux de société' },
      { code: 'game_console', label: 'Console de jeux' },
      { code: 'ping_pong', label: 'Table de ping-pong' },
      { code: 'pool_table', label: 'Billard' },
      { code: 'bikes', label: 'Vélos à disposition' },
      { code: 'kayak_paddle', label: 'Kayak / Paddle' },
    ],
  },
  {
    label: 'Enfants',
    items: [
      { code: 'high_chair', label: 'Chaise haute' },
      { code: 'travel_crib', label: 'Lit parapluie' },
      { code: 'safety_gate', label: 'Barrière de sécurité' },
      { code: 'kids_toys', label: 'Jeux enfants' },
      { code: 'secure_yard', label: 'Cour sécurisée' },
    ],
  },
  {
    label: 'Accessibilité',
    items: [
      { code: 'wheelchair_access', label: 'Accès PMR' },
      { code: 'ground_floor', label: 'Plain-pied' },
      { code: 'accessible_shower', label: 'Douche accessible' },
      { code: 'elevator', label: 'Ascenseur' },
    ],
  },
  {
    label: 'Pratique / Arrivée',
    items: [
      { code: 'self_checkin', label: 'Entrée autonome' },
      { code: 'checkin_24h', label: 'Check-in 24h' },
      { code: 'concierge', label: 'Conciergerie' },
      { code: 'workspace', label: 'Espace de travail / Bureau' },
    ],
  },
  {
    label: 'Environnement',
    items: [
      { code: 'sea_view', label: 'Vue mer' },
      { code: 'mountain_view', label: 'Vue montagne' },
      { code: 'lake_view', label: 'Vue lac' },
      { code: 'beachfront', label: 'Bord de plage' },
      { code: 'city_center', label: 'En centre-ville' },
      { code: 'quiet_area', label: 'Au calme' },
      { code: 'pets_allowed', label: 'Animaux acceptés' },
      { code: 'non_smoking', label: 'Non-fumeur' },
    ],
  },
];
